server:
  port: 8080

spring:
  application:
    name: msvc
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/students/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/courses/**
        - id: auth
          uri: 'http://localhost:7070'
          predicates:
            - Path=/auth/**
        - id: auth2
          uri: 'http://localhost:7070'
          predicates:
            - Path=/api/**
eureka:
  client:
    register-with-eureka: false