server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/studentDb
    username: root
    password: root1234
  application:
    name: msvc-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: students
            uri: 'http://localhost:8090'
            predicates:
            - Path=/api/students/**
<<<<<<< Updated upstream
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/courses/**
        - id: auth
          uri: 'http://localhost:7070'
          predicates:
            - Path=/auth/**
        - id: auth2
          uri: 'http://localhost:7070'
          predicates:
            - Path=/api/**
=======
          - id: courses
            uri: 'http://localhost:9090'
            predicates:
            - Path=/api/courses/**         
 
>>>>>>> Stashed changes
eureka:
  client:
    register-with-eureka: false
